server:
  servlet:
    session:
      cookie:
        name: ion-session
        path: /
        same-site: strict
        http-only: true
        secure: true
  error:
    include-stacktrace: never
    include-exception: false
    whitelabel:
      enabled: false
  port: 3001

  ssl:
    key-store: keystore.p12
    key-store-type: PKCS12
    key-store-password: ENC(lOWKOlRL4xM8SgMyUN3MKphm+uSL7XD1530CL9USrVklJ818/aTSptJy0dIs2rx5OYND2nm1AlQFpAhGzbkvVubGqFrHwizthuOP23fCEdE=)

spring:
  session:
    redis:
      namespace: ion:session
    timeout: 168h

  thymeleaf:
    prefix: classpath:/static/

  datasource:
    url: ENC(jAIdN34TguJjhY/iBkYO+LOFjhK8X2lbabM2v71XJlfzOzjBw8VuTGEYzlWuQC47GWnJvJPxLgLVs5H+SQkr4nrV2zheC6sfi+oeNM+BGpc=)
    username: ENC(ONGRKhokanG9GLPXTx+s/xPqb8+HappsAh8ZtPg+7inY8ZmxRuGkpz5lXQljeBXa)
    password: ENC(af64baMK8Pcp1vasX49XYo9U7ajX/MpPCyhqyz8CdlkTnqrW4zPUOCZ05aFBlB444ijhKL43J/thhcDvlFtcNiWbvXSWm9T+Y2sadO4t/6I=)
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false

  data:
    redis:
      host: localhost
      port: 8735

  mvc:
    static-path-pattern: /**
