server:
  servlet:
    session:
      cookie:
        name: ion-session
        path: /
        same-site: strict
        http-only: true
        secure: false
  error:
    include-stacktrace: never
    include-exception: false
    whitelabel:
      enabled: false
  port: 3001
  ssl:
    key-store: keystore.p12
    key-store-type: PKCS12
    key-store-password: ENC(31pZKVK5oi/ZFpZcTqSudkpIeetLZCbAE9ZqBVRnyE4KWU9E1E0Rn+YPzOa3J0e7rIsC7pMoYQBBrns/e8dyQCm4kJY0YwKsaXDq9r9uzNs=)

spring:
  devtools:
    livereload:
      enabled: true

  session:
    redis:
      namespace: ion:session
    timeout: 168h

  thymeleaf:
    prefix: classpath:/static/

  datasource:
    url: ENC(2nE60HY2+lBYeWJ0pTIX6V0HSZUeJtdA4Lc1mCXnp40ax+S2Oh6Pv/HIZmBEXeUr8wzt+y5aN3Z71i1A+bZ3pCnMRpBZXGyqUDOxMWZlcv8=)
    username: ENC(HDLfzgnQEVV6VfxrYUHdhe3712/9W3O7quPTo29HEowV3FB/t+3V5YOWBy0aXJ5o)
    password: ENC(k9f+ClZCk5uqd/zWOudFQ5naUEbK/7t4S6+5AbcQt+vsBzaDIf70u+cTUQ7mqPQvHNljd1TrvkKY3tVr825BTjETXuc9ZlOIYkVWC0TAsOY=)
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true

  data:
    redis:
      host: localhost
      port: 8735

  mvc:
    static-path-pattern: /**

ion:
  apod:
    api-key: ENC(F9RJLDmmQ410giRlINEAY9Gq3HpPuPevshQlXzjK3xhQpA9zBsbpvHUmocmNumoCSvNIKmOHZH35LybJQ50ULIKIz2WaSRZk3XVJj90Wbl8=)